# -*- coding: utf-8 -*-
"""SOMs(Self_Organizing_Maps).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EeC2wWFuU9wDJhqqXcL1_3BNol8dka3

# Self Organizing Maps (SOMs)
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Data Preprocessing"""

dataset = pd.read_csv("Credit_Card_Applications.csv")

dataset.head()

x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

"""Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
x = sc.fit_transform(x)

"""Training SOM"""

!pip install minisom
from minisom import MiniSom

som = MiniSom(x = 10, y=10, input_len = 15,sigma = 1.0, learning_rate = 0.5)
som.random_weights_init(x)
som.train_random(x, num_iteration = 100)

"""Visualization of Results"""

from pylab import bone, pcolor, colorbar, plot, show
bone()
pcolor(som.distance_map().T)
colorbar()
markers = ['o','s']
colors = ['r','g']
for i, x in enumerate(x):
  w = som.winner(x)
  plot(w[0] + 0.5,
       w[1] + 0.5,
       markers[y[i]],
       markeredgecolor = colors[y[i]],
       markerfacecolor = 'None',
       markersize = 10,
       markeredgewidth = 2)
show()